name: Stale

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          stale-issue-message: "This issue is being marked as stale because there has been no activity for 180 days. Please add a comment to keep it open."
          stale-issue-label: stale
          days-before-issue-stale: 180
          days-before-issue-close: 30

          stale-pr-message: "This PR is being marked as stale because there has been no activity for 90 days. Please add a comment to keep it open."
          stale-pr-label: stale
          days-before-pr-stale: 90
          days-before-pr-close: 30
          delete-branch: true
